theme: jekyll-theme-minimal
title: CUBRIC ITBS 2018
description: This page provides information about the CUBRIC Introduction to Brain Stimulation workshop taking place on October 5th 2018
logo: assets/cubric_large.png
